language: java
jdk:
  - openjdk8

services:
  - mysql

#addons:
#  mariadb: '10.0'

branches:
  only:
    - master

# Travis CI 서버의 HOME
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'

before_install:
  - mysql -u root -p root
  - mysql -e "use mysql; update user set authentication_string=PASSWORD('root') where User='root';"
  - mysql -e "use mysql; update user set plugin='mysql_native_password'; FLUSH PRIVILEGES;"
  - mysql -e "create database='dstar';"
  - service mysql restart

script: "./gradlew clean build"

before_deploy:
  - mkdir deploy
  - mv build/libs/*.jar deploy
  - mv appspec.yml deploy
  - mv execute-deploy.sh
  - zip dstar.zip deploy/*
  - mv dstar.zip deploy/dstar.zip

deploy:
  - provider: s3
    skip_cleanup: true
    access_key_id: $AWS_ACCESS_KEY # Travis repo settings 값
    secret_access_key: $AWS_SECRET_KEY # Travis repo settings 값
    bucket: dstar-deploy # S3 버킷명
    region: ap-northeast-2
    acl: public_read
    local_dir: deploy # before_deploy에서 생성한 디렉토리
    wait-until-deployed: true
    on:
      repo: dstar0914/dstar
      branch: master

  - provider: codedeploy
    access_key_id: $AWS_ACCESS_KEY # Travis repo settings 값
    secret_access_key: $AWS_SECRET_KEY # Travis repo settings 값
    bucket: dstar-deploy # S3 버킷명
    key: dstar.zip
    bundle_type: zip
    application: dstar-service # 웹 콘솔에서 등록한 CodeDeploy 애플리케이션
    deployment_group: dstar-service-group
    region: ap-northeast-2
    wait-until-deployed: true
    on:
      repo: dstar0914/dstar
      branch: master

# CI 실행 완료시 메일로 알람
notifications:
  email:
    recipients:
      - demon091400@gmail.com